name: logextractor docker

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean install

   - uses: actions/checkout@v4
   - name: Build the Docker image
     run: docker build . --file Dockerfile --tag logextractor:$(date +%s)
     with:
       image: talktoathulkrishna/logextractor
       tags: latest
       registry: docker.io
       dockerfile: Dockerfile.ci
       username: ${{ secrets.DOCKER_USERNAME }}
       password: ${{ secrets.DOCKER_PASSWORD }}